# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: translate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='translate.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ftranslate.proto\"\'\n\roriginal_text\x12\x16\n\x0eoriginal_text1\x18\x01 \x01(\t\"+\n\x0ftranslated_text\x12\x18\n\x10translated_text1\x18\x01 \x01(\t2:\n\x07Greeter\x12/\n\ttranslate\x12\x0e.original_text\x1a\x10.translated_text\"\x00\x62\x06proto3'
)




_ORIGINAL_TEXT = _descriptor.Descriptor(
  name='original_text',
  full_name='original_text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='original_text1', full_name='original_text.original_text1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=58,
)


_TRANSLATED_TEXT = _descriptor.Descriptor(
  name='translated_text',
  full_name='translated_text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='translated_text1', full_name='translated_text.translated_text1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['original_text'] = _ORIGINAL_TEXT
DESCRIPTOR.message_types_by_name['translated_text'] = _TRANSLATED_TEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

original_text = _reflection.GeneratedProtocolMessageType('original_text', (_message.Message,), {
  'DESCRIPTOR' : _ORIGINAL_TEXT,
  '__module__' : 'translate_pb2'
  # @@protoc_insertion_point(class_scope:original_text)
  })
_sym_db.RegisterMessage(original_text)

translated_text = _reflection.GeneratedProtocolMessageType('translated_text', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATED_TEXT,
  '__module__' : 'translate_pb2'
  # @@protoc_insertion_point(class_scope:translated_text)
  })
_sym_db.RegisterMessage(translated_text)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=105,
  serialized_end=163,
  methods=[
  _descriptor.MethodDescriptor(
    name='translate',
    full_name='Greeter.translate',
    index=0,
    containing_service=None,
    input_type=_ORIGINAL_TEXT,
    output_type=_TRANSLATED_TEXT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
