# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imagesend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imagesend.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fimagesend.proto\"!\n\nimage_name\x12\x13\n\x0bimage_name1\x18\x01 \x01(\t\"*\n\x06images\x12\x0f\n\x07images1\x18\x01 \x01(\x0c\x12\x0f\n\x07images2\x18\x02 \x01(\x0c\x32\x33\n\tImageSend\x12&\n\x0cImagerequest\x12\x0b.image_name\x1a\x07.images\"\x00\x62\x06proto3'
)




_IMAGE_NAME = _descriptor.Descriptor(
  name='image_name',
  full_name='image_name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_name1', full_name='image_name.image_name1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=52,
)


_IMAGES = _descriptor.Descriptor(
  name='images',
  full_name='images',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='images1', full_name='images.images1', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='images2', full_name='images.images2', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['image_name'] = _IMAGE_NAME
DESCRIPTOR.message_types_by_name['images'] = _IMAGES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

image_name = _reflection.GeneratedProtocolMessageType('image_name', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE_NAME,
  '__module__' : 'imagesend_pb2'
  # @@protoc_insertion_point(class_scope:image_name)
  })
_sym_db.RegisterMessage(image_name)

images = _reflection.GeneratedProtocolMessageType('images', (_message.Message,), {
  'DESCRIPTOR' : _IMAGES,
  '__module__' : 'imagesend_pb2'
  # @@protoc_insertion_point(class_scope:images)
  })
_sym_db.RegisterMessage(images)



_IMAGESEND = _descriptor.ServiceDescriptor(
  name='ImageSend',
  full_name='ImageSend',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=98,
  serialized_end=149,
  methods=[
  _descriptor.MethodDescriptor(
    name='Imagerequest',
    full_name='ImageSend.Imagerequest',
    index=0,
    containing_service=None,
    input_type=_IMAGE_NAME,
    output_type=_IMAGES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGESEND)

DESCRIPTOR.services_by_name['ImageSend'] = _IMAGESEND

# @@protoc_insertion_point(module_scope)
